# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Remove shared memory segment
#' @param segment segment name
#' @export
shm_remove_segment <- function(segment) {
    .Call(`_shm_shm_remove_segment`, segment)
}

#' Create shared memory segment
#' @param segment segment name
#' @param size initial size in bytes
#' @export
shm_create_segment <- function(segment, size) {
    invisible(.Call(`_shm_shm_create_segment`, segment, size))
}

#' Set object in shared memory
#' @param x an R object
#' @param segment a string
#' @param name a string
#' @param overwrite Overwrite segment if exists
#' @export
shm_set <- function(x, segment, name) {
    invisible(.Call(`_shm_shm_set`, x, segment, name))
}

#' Get object from shared memory
#' @param segment segment name
#' @param name object name
#' @export
shm_get <- function(segment, name) {
    .Call(`_shm_shm_get`, segment, name)
}

